<?php
/**
 * @file
 * Code for the GSB Feature Case Display feature.
 */

include_once 'gsb_feature_case_display.features.inc';

/**
 * Implements hook_form_alter().
 */
function gsb_feature_case_display_form_alter(&$form, &$form_state) {
  if (!empty($form_state['view']) && $form_state['view']->name == 'case_filters' && $form_state['view']->current_display == 'panel_pane_1') {
    // set the nids argument field into the exposed portion of the config form
    $form['arguments']['nid']['#description'] = 'Separate Node IDs with commas and no spaces.';
    $form['exposed']['arguments'] = $form['arguments'];
    $form['exposed']['arguments']['#weight'] = -98;
    $form['arguments']['#access'] = FALSE;
    $form['#validate'][] = 'gsb_feature_case_display_pane_config_validate';
  }
}

/**
 * Validate handler for views_content_views_panes_content_type_edit_form.
 *  - Stores the arguments nid field values in pane config.
 */
function gsb_feature_case_display_pane_config_validate(&$form, &$form_state) {
  $form_state['values']['arguments']['nid'] = $form_state['values']['exposed']['arguments']['nid'];
}

/**
 * Implements hook_form_FORM_ID_alter() for views_exposed_form.
 */
function gsb_feature_case_display_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['view']->name == 'gsb_case_listing') {
    $form['secondary']['availability'] = array(
      '#prefix' => '<div class="form-item form-type-select case-availability"><label>' . t('Availability') . '</label>',
      '#suffix' => '</div>',
    );

    // Loop through each availability field and group them.
    foreach (array('field_free_case_value', 'field_has_harvard_link_value', 'field_has_case_center_value') as $key) {
      if (!isset($form['secondary'][$key])) {
        continue;
      }

      $form['secondary'][$key]['#options'][1] = $form['secondary'][$key]['#title'];
      $form['secondary'][$key]['#title_display'] = 'invisible';
      $form['secondary']['availability'][$key] = $form['secondary'][$key];
      unset($form['secondary'][$key]);
    }
  }
}
