<?php
/**
 * @file
 * Code for the GSB Feature Case Display feature.
 */

include_once 'gsb_feature_case_display.features.inc';

/**
 * Implementation of hook_module_implements_alter()
 */
function gsb_feature_case_display_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter') {
    if (isset($implementations['gsb_feature_case_display'])) {
      $group = $implementations['gsb_feature_case_display'];
      unset($implementations['gsb_feature_case_display']);
      $implementations['gsb_feature_case_display'] = $group;
    }
  }
}

/**
 * Validate handler for views_content_views_panes_content_type_edit_form.
 *  - Stores the arguments nid field values in pane config.
 */
function gsb_feature_case_display_pane_config_validate(&$form, &$form_state) {
  if (!empty($form_state['values']['exposed'])) {
    $form_state['values']['arguments']['nid'] = $form_state['values']['exposed']['arguments']['nid'];
  }
}

/**
  * Implements hook_form_FORM_ID_alter().
  */
function gsb_feature_case_display_form_views_content_views_panes_content_type_edit_form_alter(&$form, &$form_state) {
  // Alter 'Case filters' content pane settings form.
  if ($form_state['pane']->subtype == 'case_filters-panel_pane_1' && $form_state['view']->name == 'case_filters' && $form_state['view']->current_display == 'panel_pane_1') {
    //Hide all display modes except compact and expanded

    $view_modes = $form['view_mode']['#options'];
    foreach($view_modes as $key=>$value) {
      if($key !== 'compact' AND $key !== 'expanded'){
        unset($form['view_mode']['#options'][$key]);
      }
    }

    $form['exposed']['widget_title']['#field_prefix'] = 'Block Title';
    // set the nids argument field into the exposed portion of the config form
    $form['arguments']['nid']['#description'] = 'Separate Node IDs with commas and no spaces.';
    $form['exposed']['filter-field_person_fac_single_ref_target_id']['#description'] = 'Enter faculty node ID.';
    $form['exposed']['arguments'] = $form['arguments'];
    $form['exposed']['arguments']['#weight'] = -97;
    $form['arguments']['#access'] = FALSE;
    $form['comments']['#access'] = FALSE;
    $form['links']['#access'] = FALSE;

    $conf = $form_state['conf'];
    $item['title_link'] = array(
      '#title' => t('URL'),
      '#type' => 'textfield',
      '#weight' => -98,
      '#default_value' => !empty($conf['title_link']) ? $conf['title_link'] : '',
    );
    $form['override_title']['#weight'] = -99;
    $form['items_per_page']['#weight'] = -96;
    $form['view_mode']['#weight'] = -95;
    $form['exposed']['#weight'] = -94;

    $form = gsb_misc_fixes_associative_insert($form, 'override_title_text', $item);

    $form['#validate'][] = 'gsb_feature_case_display_pane_config_validate';
    $form['#submit'][] = 'case_filters_pane_config_submit';
  }
}

/**
 * Submit handler for views_content_views_panes_content_type_edit_form.
 *  - Save title link field in pane config.
 */
function case_filters_pane_config_submit($form, &$form_state) {
  $form_state['conf']['title_link'] = $form_state['values']['title_link'];
}

/**
 * Implements hook_panels_pane_content_alter().
 *  - Alter Case Filters content pane title to be linked to a custom URL.
 */
function gsb_feature_case_display_panels_pane_content_alter($content, $pane, $args, $context) {
  if ($content && $content->subtype == 'case_filters-panel_pane_1') {
    if (!empty($pane->configuration['title_link'])) {
      $content->title = l($content->title, $pane->configuration['title_link']);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for views_exposed_form.
 */
function gsb_feature_case_display_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {
  if ($form_state['view']->name == 'gsb_case_listing') {
    $form['secondary']['availability'] = array(
      '#prefix' => '<div class="form-item form-type-select case-availability"><label>' . t('Availability') . '</label>',
      '#suffix' => '</div>',
    );

    // Loop through each availability field and group them.
    foreach (array('field_free_case_value', 'field_has_harvard_link_value', 'field_has_case_center_value') as $key) {
      if (!isset($form['secondary'][$key])) {
        continue;
      }

      $form['secondary'][$key]['#options'][1] = $form['secondary'][$key]['#title'];
      $form['secondary'][$key]['#title_display'] = 'invisible';
      $form['secondary']['availability'][$key] = $form['secondary'][$key];
      unset($form['secondary'][$key]);
    }
  }
}
